Create Budget Web application
tjay1760/Budget-App pull request #1
Opened 2023-10-20 10:26 UTC by tjay1760

# In this pull request I created a budget App with the following specifications: 

### Splash screen

A simple page with the name of my app and links to the sign up and log in pages.

### Sign up and log in pages

The user is able to register in the app with full name, email and password 
The user can log into the app using email and password.
If the user is not logged in, they can't access pages that require the user to be logged in 

### Home page (categories page)

When the user logs in, they are presented with the categories page.
For each category, the user can see their name, icon and the total amount of all the transactions that belongs to that category.
When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
There is a button "add a new category" at the bottom that brings the user to the page to create a new category.

### Transactions page

For a given category, the list of transactions is presented, ordered by the most recent.
At the top of the page the user could see the total amount for the category (sum of all of the amounts of the transactions in that category).
There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.
When the user clicks on the "Back" button (<), the user navigates to the home page.

### "Add a new category" page

The user fills out a form to create a new category, indicating their name and icon (both mandatory).
The user clicks (or taps) the "Save" button to create the new category, and is taken to the home page on success.
When the user clicks on the "Back" button (<), the user navigates to the home page.

### "Add a new transaction" page

The user fills out a form to create a new transaction with:
name 
amount 
categories 
The user clicks (or taps) the "Save" button to create the new transaction, and is taken to the transactions page for that category.
When the user clicks on the "Back" button (<), the user navigates to the transactions page for that category.
I also created unit and integration tests for all the most important components of the application.

### Other technical features

I used Postgres as your database.
I used devise for authentication.
I validated all user input to make sure that anyone with bad intentions cannot compromise the app.
The project  deployed and accessible online here: https://budgetapp-g2pb.onrender.com.

2023-10-20 12:13 UTC, fobadara requested changes
Hi @tjay1760, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![REDO](https://user-images.githubusercontent.com/62938735/260208741-25cd532c-dea0-4827-bb4f-5412e8493916.gif)

## Highlights
✅ Descriptive README
✅ Descriptive PR summary
✅ Clean code
✅ Good first attempt
✅ Good implementation of the principle of separating concerns.
✅ Use of rails partials
✅ All specs are passing

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-20 12:13 UTC, fobadara commented on README.md
> +## 🙏 Acknowledgments <a name="acknowledgements"></a>
[REQUIRED] Kindly give proper credit to Gregoire Vella the owner of the design according to  the [Creative Commons License](https://creativecommons.org/licenses/by-nc/4.0/)

2023-10-20 12:13 UTC, fobadara commented on app/views/main/index.html.erb
[REQUIRED] Kindly ensure that your design matches the template in terms of colour typography and layout. Kindly centre the app name and ensure that the login nad signup buttons are at the bottom.

![image](https://github.com/tjay1760/Budget-App/assets/62938735/29ec99c7-2dfd-4620-a0cd-7c47e4c91283)

[OPTIONAL] I noticed that you considered another page as the splash page but based on the instructions the splash page is supposed to contain your app name and the login and signup buttons.

2023-10-20 12:13 UTC, fobadara commented on app/views/devise/registrations/new.html.erb
[REQUIRED] Kindly ensure that your signup page looks like the template in the image below. You should have the `Register` button in the center, your submit button should be the `Next` button on the top right of the template, Your inputs should fill the width of the screen and not have spaces

![image](https://github.com/tjay1760/Budget-App/assets/62938735/9efca4f5-fea4-437e-a880-9f3bff332296)

[REQUIRED] Also look at the image below for other required changes:
![image](https://github.com/tjay1760/Budget-App/assets/62938735/cae4e023-0c3b-460a-afb6-76cf75725568)

2023-10-20 12:13 UTC, fobadara commented on app/views/devise/sessions/new.html.erb
[REQUIRED] Kindly ensure that your design matches the template in terms of colour, typography and layout. Kindly look at the image below and make adjustments as specified:
![image](https://github.com/tjay1760/Budget-App/assets/62938735/c39cb0c4-b42d-4314-ad7d-d2c8b41cde58)

2023-10-20 12:13 UTC, fobadara commented on app/views/categories/index.html.erb
> +  <%= link_to "New category", new_category_path, class: "link_to newcat" %>
[REQUIRED] Kindly move your `new category` button to the bottom of the page. It should be replacing the scan button.
![image](https://github.com/tjay1760/Budget-App/assets/62938735/95fed736-a3d3-444d-afe0-0640ab968343)

2023-10-20 12:13 UTC, fobadara commented on app/views/categories/index.html.erb
> +    <% end %>
[REQUIRED] Please ensure that your design matches the template. Kindly look at the image below:
![image](https://github.com/tjay1760/Budget-App/assets/62938735/ec456256-1275-46e0-8a40-f5bf00930546)

2023-10-20 12:13 UTC, fobadara commented on app/views/expenses/index.html.erb
[REQUIRED] Kindly ensure that the design for your transaction page looks more like the transaction or details page in the Behance template in terms of colour, typography and especially layout. The general layout doesn't look like any of them

[REQUIRED] When I try to create an expense without selecting a category I get the error in the image below. Kindly fix this problem and ensure that the user can't submit the form without selecting at least one category.

![image](https://github.com/tjay1760/Budget-App/assets/62938735/1b11e506-fd76-4b63-b785-653a7cbc9b19)

2023-10-20 12:13 UTC, fobadara commented on config/routes.rb
> +  resources :categories, only: %i[index new create update show destroy]  do
[REQUIRED] You include an update under the created resources even though you have no action for it in your controller. Kindly ensure that you are creating only resources that are used.

2023-10-20 12:13 UTC, fobadara commented on app/controllers/categories_controller.rb
> +    end
[REQUIRED] What happens when there is an error? Kindly include a fail path for this action.

2023-10-20 12:13 UTC, fobadara commented on app/controllers/expenses_controller.rb
> +    end
[REQUIRED] Kindly include a fail path that handles errors. This makes your code more professional, saves it from breaking and helps create a good user experience

2023-10-20 12:13 UTC, fobadara commented on config/routes.rb
> +  resources :expenses , only: %i[index new create destroy]
[REQUIRED] I can see an update action in your expenses controller but I cant see the route. Kindly include it or remove the action from the controller.

2023-10-21 14:55 UTC, tugsem requested changes
## STATUS: REQUIRED CHANGES ♻️
Hello @tjay1760 👋 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are some issues that you still need to work on to go to the next project but you are almost there!

![ Alt Text](https://media.giphy.com/media/l2Je9zHYveK012EVi/giphy.gif)

 ## Highlights 🚀
✔️Good job on making the changes

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-21 14:55 UTC, tugsem commented on README.md
> +Original design idea by Gregoire Vella on Behance.
- [ ]  As requested before, kindly move this line to the acknowledgments section.

2023-10-21 14:55 UTC, tugsem commented on app/views/categories/index.html.erb
> +  <%= link_to "New category", new_category_path, class: "link_to newcat" %>
- [ ] As requested, please move this button to the bottom of the page to match the design.
![image](https://github.com/tjay1760/Budget-App/assets/91486791/164ff739-fb9d-4c7c-8f55-a555fec4fcc1)

2023-10-21 14:55 UTC, tugsem commented on app/views/categories/index.html.erb
> +          <%= link_to render(category), category_path(category), class: "link_to cats" %>
- [ ] As requested, please increase the size of the image of the category to match the given design.
![image](https://github.com/tjay1760/Budget-App/assets/91486791/1d9687cd-b973-4349-9ed1-fb07d63ef805)

2023-10-21 14:55 UTC, tugsem commented on config/routes.rb
> +  resources :categories, only: %i[index new create update show destroy]  do
- [ ] As requested, kindly remove the 'update' action from the categories route as you don't have it.

2023-10-21 14:55 UTC, tugsem commented on config/routes.rb
> +  resources :expenses , only: %i[index new create destroy]
- [ ] As requested, please add the 'update' action here as you have it in your controller, or remove it.

2023-10-21 14:55 UTC, tugsem commented on app/controllers/categories_controller.rb
> +    end
- [ ] As requested, please handle the case of an error in this request(destroy).
https://github.com/tjay1760/Budget-App/pull/1/files/25ed052ce28d3025370ee0db010779aa76358fff#r1366886142

2023-10-21 14:55 UTC, tugsem commented on app/controllers/expenses_controller.rb
> +    end
- [ ] As requested, please handle the error for this action. 
https://github.com/tjay1760/Budget-App/pull/1#discussion_r1366887946

2023-10-21 17:27 UTC, Owusu-Desmond approved these changes
Hi @tjay1760 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-21 17:36 UTC, merged